package com.sentry.chat.model;

import com.sentry.user.dto.UserResponse;
import lombok.*;

import java.time.LocalDateTime;
import java.util.List;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Chat {
    /*
     * Id of the chat.
     * Generated by the database.
     * Read-only.
     */
    private Long id;

    /*
     * Date and time of chat creation.
     * Generated by the database.
     * Read-only.
     */
    private LocalDateTime createdAt;

    /*
     * List of participant user profiles in this chat.
     * Read-only.
     */
    private List<UserResponse> participants;

    /*
     * Most recent message in this chat (null if no messages sent yet).
     * Read-only.
     */
    private Message lastMessage;
}
