package com.sentry.chat.model;

import com.sentry.user.dto.UserResponse;
import lombok.*;

import java.time.LocalDateTime;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ChatParticipant {
    /*
     * Id of the chat.
     * Generated by the database.
     * Read-only.
     */
    private Long chatId;

    /*
     * Id of the participating user.
     * Read-only.
     */
    private Long userId;

    /*
     * Date and time the user joined the chat.
     * Generated by the database.
     * Read-only.
     */
    private LocalDateTime joinedAt;

    /*
     * User profile of the participant.
     * Read-only.
     */
    private UserResponse user;
}
