package com.sentry.chat.model;

import com.sentry.user.dto.UserResponse;
import lombok.*;

import java.time.LocalDateTime;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Message {
    /*
     * Id of the message.
     * Generated by the database.
     * Read-only.
     */
    private Long id;

    /*
     * Id of the parent chat.
     * Read-only.
     */
    private Long chatId;

    /*
     * Id of the sender.
     * Read-only.
     */
    private Long senderId;

    /*
     * Base64 encoded ciphertext of the message.
     * Cannot be null.
     * Cannot be empty.
     */
    private String ciphertext;

    /*
     * Date and time of message creation.
     * Generated by the database.
     * Read-only.
     */
    private LocalDateTime createdAt;

    /*
     * User profile of the sender.
     * Read-only.
     */
    private UserResponse sender;
}
