package com.sentry.user.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import java.time.LocalDateTime;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User {
    /*
     * Id of the user.
     * Generated by the database.
     * Read-only.
     */
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private Long id;

    /*
     * Username of the user.
     * Cannot be changed after creation.
     * Cannot be null.
     * Cannot be empty.
     * Cannot be longer than 32 characters.
     */
    @NotBlank(message = "Username cannot be blank")
    @Size(min = 3, max = 32, message = "Username cannot exceed 32 characters")
    @Pattern(regexp = "^[a-zA-Z0-9_-]+$", message = "Username can only contain alphanumeric characters, hyphens, and underscores")
    private String username;

    /*
     * Display name of the user.
     * Can be changed after creation.
     * Cannot be null.
     * Cannot be empty.
     * Cannot be longer than 50 characters.
     */
    @NotBlank(message = "Display name cannot be blank")
    @Size(max = 50, message = "Display name cannot exceed 50 characters")
    private String displayName;

    /*
     * Hashed password of the user.
     * Cannot be changed after creation.
     * Cannot be null.
     * Cannot be empty.
     * Cannot be longer than 255 characters.
     */
    @NotBlank(message = "Password hash cannot be blank")
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    private String passwordHash;

    /*
     * Date and time of user creation.
     * Generated by the database.
     * Read-only.
     */
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private LocalDateTime createdAt;
}
