package com.sentry.user.model;

import lombok.*;
import java.time.LocalDateTime;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User {
    /*
     * Id of the user.
     * Generated by the database.
     * Read-only.
     */
    private Long id;

    /*
     * Username of the user.
     * Cannot be changed after creation.
     * Cannot be null.
     * Cannot be empty.
     * Cannot be longer than 32 characters.
     */
    private String username;

    /*
     * Display name of the user.
     * Can be changed after creation.
     * Cannot be null.
     * Cannot be empty.
     * Cannot be longer than 50 characters.
     */
    private String displayName;

    /*
     * Hashed password of the user.
     * Cannot be changed after creation.
     * Cannot be null.
     * Cannot be empty.
     * Cannot be longer than 255 characters.
     */
    private String passwordHash;

    /*
     * Date and time of user creation.
     * Generated by the database.
     * Read-only.
     */
    private LocalDateTime createdAt;
}
