package com.sentry.user.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.*;
import java.time.LocalDateTime;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User {
    /*
     * Id of the user.
     * Generated by the database.
     * Read-only.
     */
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private Long id;

    /*
     * Username of the user.
     * Cannot be changed after creation.
     * Cannot be null.
     * Cannot be empty.
     * Cannot be longer than 32 characters.
     */
    private String username;

    /*
     * Display name of the user.
     * Can be changed after creation.
     * Cannot be null.
     * Cannot be empty.
     * Cannot be longer than 50 characters.
     */
    private String displayName;

    /*
     * Hashed password of the user.
     * Cannot be changed after creation.
     * Cannot be null.
     * Cannot be empty.
     * Cannot be longer than 255 characters.
     */
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    private String passwordHash;

    /*
     * Date and time of user creation.
     * Generated by the database.
     * Read-only.
     */
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private LocalDateTime createdAt;
}
