package com.sentry.friend.model;

import lombok.*;
import java.time.LocalDateTime;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Friendship {
    /*
     * Id of user 1 in the friendship (always smaller than user2).
     * Generated by the database.
     * Read-only.
     */
    private Long userId1;

    /*
     * Id of user 2 in the friendship (always greater than user1).
     * Generated by the database.
     * Read-only.
     */
    private Long userId2;

    /*
     * Date and time of friendship creation.
     * Generated by the database.
     * Read-only.
     */
    private LocalDateTime createdAt;
}
