package com.sentry.friend.model;

import com.sentry.user.dto.UserResponse;
import lombok.*;
import java.time.LocalDateTime;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class FriendRequest {
    /*
     * Id of the friend request.
     * Generated by the database.
     * Read-only.
     */
    private Long id;

    /*
     * User ID of the sender.
     */
    private Long senderId;

    /*
     * User ID of the receiver.
     */
    private Long receiverId;

    /*
     * Status of the friend request (pending, accepted, declined, or cancelled).
     */
    private String status;

    /*
     * Date and time of creation.
     * Generated by the database.
     * Read-only.
     */
    private LocalDateTime createdAt;

    /*
     * Date and time of last update.
     * Generated by the database.
     * Read-only.
     */
    private LocalDateTime updatedAt;

    /*
     * Sender user profile.
     * Read-only.
     */
    private UserResponse sender;

    /*
     * Receiver user profile.
     * Read-only.
     */
    private UserResponse receiver;
}
